### ISSUE TITLE
Crash with KeyError: 'openssl'

### ISSUE THREAD

**Issue by cFire** [stampery/mongoaudit#19]
Not sure if this is some dependency error or an application bug. I got this same error on Arch Linux and Debian 8.

```
$ ./mongoaudit-linux 
Traceback (most recent call last):
  File "mongoaudit", line 31, in <module>
  File "src/main.py", line 62, in main
  File "src/main.py", line 22, in __init__
  File "src/main.py", line 57, in main
  File "urwid/main_loop.py", line 278, in run
  File "urwid/main_loop.py", line 376, in _run
  File "urwid/main_loop.py", line 682, in run
  File "urwid/main_loop.py", line 719, in _loop
  File "urwid/raw_display.py", line 393, in <lambda>
  File "urwid/raw_display.py", line 493, in parse_input
  File "urwid/main_loop.py", line 403, in _update
  File "urwid/main_loop.py", line 503, in process_input
  File "urwid/container.py", line 592, in keypress
  File "urwid/container.py", line 1587, in keypress
  File "src/widgets.py", line 213, in keypress
  File "urwid/container.py", line 1587, in keypress
  File "urwid/decoration.py", line 621, in keypress
  File "urwid/container.py", line 1587, in keypress
  File "urwid/container.py", line 1587, in keypress
  File "src/widgets.py", line 147, in keypress
  File "src/widgets.py", line 183, in next
  File "src/cards.py", line 90, in <lambda>
  File "src/tools.py", line 41, in validate_uri
  File "src/cards.py", line 90, in <lambda>
  File "src/cards.py", line 110, in run_test
  File "src/widgets.py", line 264, in run
  File "src/testers/testers.py", line 38, in run
  File "src/testers/testers.py", line 124, in run
  File "src/testers/testers.py", line 211, in <lambda>
KeyError: 'openssl'
Failed to execute script mongoaudit
```

**Comment by cFire** [comment]
Crash happens on the basic test step 5/18. (Maybe 6/18 if the test is started and crashed before the interface updates.)
