### ISSUE TITLE
mongoaudit aborts during step 7

### ISSUE THREAD

**Issue by sirfd** [stampery/mongoaudit#25]
mongoaudit run from Kali / Debian OS to target on CentOS.

the below error message occurs on step 7 of 20:

Traceback (most recent call last):
  File "/usr/local/bin/mongoaudit", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/__main__.py", line 63, in main
    App().main()
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/__main__.py", line 23, in __init__
    self.main()
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/__main__.py", line 58, in main
    self.loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 592, in keypress
    *self.calculate_padding_filler(size, True)), key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/widgets.py", line 220, in keypress
    return self.__super.keypress(size, key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/widgets.py", line 145, in keypress
    self.next_callback()
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/widgets.py", line 184, in next
    self.callbacks['next'](form=self, **(self.get_field_values()))
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/cards.py", line 99, in _next
    self.run_test(cred, title, tester, tests)
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/cards.py", line 127, in run_test
    test_runner.run(self.app)
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/widgets.py", line 271, in run
    self.tester.run(self.each, self.end)
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/testers/testers.py", line 45, in run
    res = test.run()
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/testers/testers.py", line 159, in run
    result = TEST_FUNCTIONS[self.name](self)
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/testers/tls.py", line 40, in valid
    cert = socket_info.sock.getpeercert()
AttributeError: '_socketobject' object has no attribute 'getpeercert'

**Comment by andymartin-sch** [comment]
```
$ mkvirtualenv mongoaudit
(mongoaudit) $ pip install mongoaudit
(mongoaudit) $ mongoaudit  [ triggers menu, but throws this error on step 7: ]
Traceback (most recent call last):
  File "~/.virtualenvs/mongoaudit/bin/mongoaudit", line 11, in <module>
    sys.exit(main())
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/mongoaudit/__main__.py", line 63, in main
    App().main()
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/mongoaudit/__main__.py", line 23, in __init__
    self.main()
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/mongoaudit/__main__.py", line 58, in main
    self.loop.run()
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/urwid/container.py", line 592, in keypress
    *self.calculate_padding_filler(size, True)), key)
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/mongoaudit/widgets.py", line 220, in keypress
    return self.__super.keypress(size, key)
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/mongoaudit/widgets.py", line 145, in keypress
    self.next_callback()
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/mongoaudit/widgets.py", line 184, in next
    self.callbacks['next'](form=self, **(self.get_field_values()))
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/mongoaudit/cards.py", line 99, in _next
    self.run_test(cred, title, tester, tests)
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/mongoaudit/cards.py", line 127, in run_test
    test_runner.run(self.app)
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/mongoaudit/widgets.py", line 271, in run
    self.tester.run(self.each, self.end)
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/mongoaudit/testers/testers.py", line 45, in run
    res = test.run()
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/mongoaudit/testers/testers.py", line 159, in run
    result = TEST_FUNCTIONS[self.name](self)
  File "~/.virtualenvs/mongoaudit/local/lib/python2.7/site-packages/mongoaudit/testers/tls.py", line 40, in valid
    cert = socket_info.sock.getpeercert()
AttributeError: '_socketobject' object has no attribute 'getpeercert'

(mongoaudit) $ pip freeze
mongoaudit==0.0.3
pymongo==3.4.0
urwid==1.3.1
wheel==0.26.0
You are using pip version 8.0.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```
