### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by drorasaf** [stampery/mongoaudit#32]
It currently declares it support python 3 although it is not

**Comment by aesedepece** [comment]
Sorry, where is python 3 declared to be supported? :open_mouth:

**Comment by drorasaf** [comment]
config.py does not include it, however, when pip install using python3, downloads it
I will definitely create a PR for this support

**Comment by 1oglop1** [comment]
@aesedepece Could you please add warning that it supports legacy python only?
I installed it into my pipenv and I'm using Py3

running command `mongoaudit`
resulted in
```
Traceback (most recent call last):
  File "/Users/jangazda/.virtualenvs/mongoaudit-OwYVqVCa/bin/mongoaudit", line 7, in <module>
    from mongoaudit.__main__ import main
  File "/Users/jangazda/.virtualenvs/mongoaudit-OwYVqVCa/lib/python3.6/site-packages/mongoaudit/__main__.py", line 18
    self.version = __version__
```
