### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wifislax** [stampery/mongoaudit#34]
kali2016 + python2.7

Traceback (most recent call last):
  File "/usr/local/bin/mongoaudit", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/__main__.py", line 63, in main
    App().main()
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/__main__.py", line 23, in __init__
    self.main()
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/__main__.py", line 58, in main
    self.loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 592, in keypress
    *self.calculate_padding_filler(size, True)), key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/widgets.py", line 220, in keypress
    return self.__super.keypress(size, key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/widgets.py", line 145, in keypress
    self.next_callback()
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/widgets.py", line 184, in next
    self.callbacks['next'](form=self, **(self.get_field_values()))
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/cards.py", line 99, in _next
    self.run_test(cred, title, tester, tests)
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/cards.py", line 127, in run_test
    test_runner.run(self.app)
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/widgets.py", line 271, in run
    self.tester.run(self.each, self.end)
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/testers/testers.py", line 45, in run
    res = test.run()
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/testers/testers.py", line 159, in run
    result = TEST_FUNCTIONS[self.name](self)
  File "/usr/local/lib/python2.7/dist-packages/mongoaudit/testers/tls.py", line 40, in valid
    cert = socket_info.sock.getpeercert()
AttributeError: '_socketobject' object has no attribute 'getpeercert'

**Comment by phenomax** [comment]
I also encounter the same issue!

**Comment by phenomax** [comment]
![image](https://user-images.githubusercontent.com/12475496/29008141-e4bd6b86-7b11-11e7-9d04-2962c5fdb97c.png)
It failes during this check

**Comment by phenomax** [comment]
Any progress here? @elecay
