### ISSUE TITLE
Mongoaudit on arch linux using black arch

### ISSUE THREAD

**Issue by dummys** [stampery/mongoaudit#35]
Hi, when launching I get the following error:

Traceback (most recent call last):
  File "mongoaudit/__main__.py", line 66, in <module>
  File "mongoaudit/__main__.py", line 63, in main
  File "mongoaudit/__main__.py", line 23, in __init__
  File "mongoaudit/__main__.py", line 58, in main
  File "site-packages/urwid/main_loop.py", line 278, in run
  File "site-packages/urwid/main_loop.py", line 376, in _run
  File "site-packages/urwid/main_loop.py", line 682, in run
  File "site-packages/urwid/main_loop.py", line 710, in _loop
  File "site-packages/urwid/main_loop.py", line 671, in _entering_idle
  File "site-packages/urwid/main_loop.py", line 564, in entering_idle
  File "site-packages/urwid/main_loop.py", line 578, in draw_screen
  File "site-packages/urwid/widget.py", line 141, in cached_render
  File "site-packages/urwid/decoration.py", line 225, in render
  File "site-packages/urwid/widget.py", line 141, in cached_render
  File "site-packages/urwid/container.py", line 787, in render
  File "site-packages/urwid/canvas.py", line 1147, in CanvasOverlay
  File "site-packages/urwid/canvas.py", line 743, in overlay
AssertionError: top canvas of overlay not the size expected!(21, 0, -2, 21)
Failed to execute script __main__

Tried with pip, same error.

**Comment by elecay** [comment]
Try making your terminal bigger (this is, drag&drog the window from a corner).

**Comment by elecay** [comment]
We're closing this since we don't get any feedback from you.
