### ISSUE TITLE
crash on test 7

### ISSUE THREAD

**Issue by khannavin** [stampery/mongoaudit#48]
```root@vagrant:/etc/apt/sources.list.d# mongoaudit
Traceback (most recent call last):
  File "/usr/local/bin/mongoaudit", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/mongoaudit/__main__.py", line 64, in main
    App().main()
  File "/usr/local/lib/python3.6/dist-packages/mongoaudit/__main__.py", line 23, in __init__
    self.main()
  File "/usr/local/lib/python3.6/dist-packages/mongoaudit/__main__.py", line 58, in main
    self.loop.run()
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib/python3.6/dist-packages/urwid/raw_display.py", line 417, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/lib/python3.6/dist-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/local/lib/python3.6/dist-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/lib/python3.6/dist-packages/urwid/container.py", line 599, in keypress
    *self.calculate_padding_filler(size, True)), key)
  File "/usr/local/lib/python3.6/dist-packages/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/local/lib/python3.6/dist-packages/mongoaudit/widgets.py", line 220, in keypress
    return self.__super.keypress(size, key)
  File "/usr/local/lib/python3.6/dist-packages/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/local/lib/python3.6/dist-packages/urwid/decoration.py", line 622, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/local/lib/python3.6/dist-packages/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/local/lib/python3.6/dist-packages/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/local/lib/python3.6/dist-packages/mongoaudit/widgets.py", line 145, in keypress
    self.next_callback()
  File "/usr/local/lib/python3.6/dist-packages/mongoaudit/widgets.py", line 184, in next
    self.callbacks['next'](form=self, **(self.get_field_values()))
  File "/usr/local/lib/python3.6/dist-packages/mongoaudit/cards.py", line 101, in _next
    self.run_test(cred, title, tester, tests)
  File "/usr/local/lib/python3.6/dist-packages/mongoaudit/cards.py", line 129, in run_test
    test_runner.run(self.app)
  File "/usr/local/lib/python3.6/dist-packages/mongoaudit/widgets.py", line 271, in run
    self.tester.run(self.each, self.end)
  File "/usr/local/lib/python3.6/dist-packages/mongoaudit/testers/testers.py", line 45, in run
    res = test.run()
  File "/usr/local/lib/python3.6/dist-packages/mongoaudit/testers/testers.py", line 161, in run
    test_result = TEST_FUNCTIONS[self.test_name](self)
  File "/usr/local/lib/python3.6/dist-packages/mongoaudit/testers/decorators.py", line 6, in userinfo_available
    return func(test) if test.tester.info else 3
  File "/usr/local/lib/python3.6/dist-packages/mongoaudit/testers/tls.py", line 25, in enabled
    with test.tester.conn._socket_for_writes() as socket_info:
TypeError: _socket_for_writes() missing 1 required positional argument: 'session'
root@vagrant:/etc/apt/sources.list.d# python --version
Python 3.6.9
root@vagrant:/etc/apt/sources.list.d# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
root@vagrant:/etc/apt/sources.list.d#```

**Comment by elecay** [comment]
This issue is already fixed. I have no permission to update pip with the new version. You can download the latest release from here: https://github.com/stampery/mongoaudit/archive/0.1.1.zip

Then:

1. Remove previous installation
2. Unzip the zip file. Go to the folder `mongoaudit-0.1.1` and run: `python setup.py install`
3. Run `mongoaudit`
