### ISSUE TITLE
Unknown ssl cer error

### ISSUE THREAD

**Issue by neelkumars** [stampery/mongoaudit#54]
/usr/local/lib/python3.10/dist-packages/mongoaudit-0.1.1-py3.10.egg/mongoaudit/widgets.py:144: SyntaxWarning: "is" with a literal. Did you mean "=="?
/usr/local/lib/python3.10/dist-packages/mongoaudit-0.1.1-py3.10.egg/mongoaudit/widgets.py:394: SyntaxWarning: "is" with a literal. Did you mean "=="?
/usr/local/lib/python3.10/dist-packages/mongoaudit-0.1.1-py3.10.egg/mongoaudit/widgets.py:400: SyntaxWarning: "is" with a literal. Did you mean "=="?
/usr/local/lib/python3.10/dist-packages/mongoaudit-0.1.1-py3.10.egg/mongoaudit/widgets.py:144: SyntaxWarning: "is" with a literal. Did you mean "=="?
/usr/local/lib/python3.10/dist-packages/mongoaudit-0.1.1-py3.10.egg/mongoaudit/widgets.py:394: SyntaxWarning: "is" with a literal. Did you mean "=="?
/usr/local/lib/python3.10/dist-packages/mongoaudit-0.1.1-py3.10.egg/mongoaudit/widgets.py:400: SyntaxWarning: "is" with a literal. Did you mean "=="?
Traceback (most recent call last):
  File "/usr/local/bin/mongoaudit", line 33, in <module>
    sys.exit(load_entry_point('mongoaudit==0.1.1', 'console_scripts', 'mongoaudit')())
  File "/usr/local/lib/python3.10/dist-packages/mongoaudit-0.1.1-py3.10.egg/mongoaudit/__main__.py", line 64, in main
  File "/usr/local/lib/python3.10/dist-packages/mongoaudit-0.1.1-py3.10.egg/mongoaudit/__main__.py", line 23, in __init__
  File "/usr/local/lib/python3.10/dist-packages/mongoaudit-0.1.1-py3.10.egg/mongoaudit/__main__.py", line 58, in main
  File "/usr/local/lib/python3.10/dist-packages/urwid-2.1.2-py3.10-linux-x86_64.egg/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/local/lib/python3.10/dist-packages/urwid-2.1.2-py3.10-linux-x86_64.egg/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.10/dist-packages/urwid-2.1.2-py3.10-linux-x86_64.egg/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/local/lib/python3.10/dist-packages/urwid-2.1.2-py3.10-linux-x86_64.egg/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib/python3.10/dist-packages/urwid-2.1.2-py3.10-linux-x86_64.egg/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/local/lib/python3.10/dist-packages/urwid-2.1.2-py3.10-linux-x86_64.egg/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/lib/python3.10/dist-packages/urwid-2.1.2-py3.10-linux-x86_64.egg/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/local/lib/python3.10/dist-packages/urwid-2.1.2-py3.10-linux-x86_64.egg/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/lib/python3.10/dist-packages/urwid-2.1.2-py3.10-linux-x86_64.egg/urwid/container.py", line 598, in keypress
    return self.top_w.keypress(self.top_w_size(size,
  File "/usr/local/lib/python3.10/dist-packages/urwid-2.1.2-py3.10-linux-x86_64.egg/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/local/lib/python3.10/dist-packages/mongoaudit-0.1.1-py3.10.egg/mongoaudit/widgets.py", line 220, in keypress
  File "/usr/local/lib/python3.10/dist-packages/urwid-2.1.2-py3.10-linux-x86_64.egg/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/local/lib/python3.10/dist-packages/urwid-2.1.2-py3.10-linux-x86_64.egg/urwid/decoration.py", line 622, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/local/lib/python3.10/dist-packages/urwid-2.1.2-py3.10-linux-x86_64.egg/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/local/lib/python3.10/dist-packages/urwid-2.1.2-py3.10-linux-x86_64.egg/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/local/lib/python3.10/dist-packages/mongoaudit-0.1.1-py3.10.egg/mongoaudit/widgets.py", line 145, in keypress
  File "/usr/local/lib/python3.10/dist-packages/mongoaudit-0.1.1-py3.10.egg/mongoaudit/widgets.py", line 184, in next
  File "/usr/local/lib/python3.10/dist-packages/mongoaudit-0.1.1-py3.10.egg/mongoaudit/cards.py", line 99, in _next
  File "/usr/local/lib/python3.10/dist-packages/mongoaudit-0.1.1-py3.10.egg/mongoaudit/testers/testers.py", line 32, in __init__
  File "/usr/local/lib/python3.10/dist-packages/mongoaudit-0.1.1-py3.10.egg/mongoaudit/testers/testers.py", line 77, in get_connection
  File "/usr/local/lib/python3.10/dist-packages/mongoaudit-0.1.1-py3.10.egg/mongoaudit/testers/testers.py", line 86, in get_tls_connection
  File "/home/satya/.local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 771, in __init__
    dict(common.validate(keyword_opts.cased_key(k), v) for k, v in keyword_opts.items())
  File "/home/satya/.local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 771, in <genexpr>
    dict(common.validate(keyword_opts.cased_key(k), v) for k, v in keyword_opts.items())
  File "/home/satya/.local/lib/python3.10/site-packages/pymongo/common.py", line 780, in validate
    value = validator(option, value)
  File "/home/satya/.local/lib/python3.10/site-packages/pymongo/common.py", line 159, in raise_config_error
    raise ConfigurationError("Unknown option %s" % (key,))
pymongo.errors.ConfigurationError: Unknown option ssl_cert_reqs

Please provide the solution for the same issue.

**Comment by Kr0n0** [comment]
You can fix it with forcing the pymongo version to 3.9.0 on setup.py:

```
     install_requires=[
-        'pymongo>=3.9.0',
+        'pymongo==3.9.0',
```

**Comment by gouthucr13** [comment]
Hi @Kr0n0  I'm also facing similar issue even after updating pymongo==3.9.0 as mentioned by you in the above comment. I'm using kali linux to scan mongodb using mongoaudit tool
